apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicorp/http-echo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hashicorp/http-echo
    ports:
    - port: 5678
      targetPort: 8080
  template:
    metadata:
      labels:
        app: hashicorp/http-echo
    spec:
      containers:
        - name: echo-hashicorp
          image: hashicorp/http-echo:latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hashicorp/http-echo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: hashicorp/http-echo
  targetNamespace: app